name: Deploy Backend (Self-Hosted)

on:
  push:
    branches: [ "main" ]

env:
  # We use the GitHub Container Registry (Free)
  REGISTRY: ghcr.io
  IMAGE_NAME: callitask/finance-api

jobs:
  build-and-deploy:
    # CRITICAL: This tells GitHub to use YOUR server, not their cloud runners
    runs-on: self-hosted
    
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Java (The runner will download JDK automatically)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build Application (Create the WAR file)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Log in to GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # 6. Deploy (Restart Containers)
      - name: Deploy to Production
        run: |
          echo "Deploying to Production..."
          cd /opt/treishvaam
          
          # Pull the new image we just pushed
          docker compose pull backend
          
          # Restart the backend service with the new image
          # --remove-orphans cleans up old containers
          docker compose up -d --remove-orphans backend
          
          # Clean up old images to save disk space
          docker image prune -f