package com.treishvaam.financeapi.service;

import com.treishvaam.financeapi.model.BlogPost;
import com.treishvaam.financeapi.model.PostStatus;
import com.treishvaam.financeapi.repository.BlogPostRepository;
import java.util.List;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/**
 * AI-CONTEXT:
 *
 * <p>Purpose: - Generates Enterprise Generative Engine Optimization (GEO) payloads.
 *
 * <p>Scope: - Orchestrates semantic data structures tailored exclusively for AI RAG ingestion.
 *
 * <p>Critical Dependencies: - GeoOptimizationController: Exposes these payloads to the edge.
 *
 * <p>Security Constraints: - Data output here must be 100% public. No PII or secure endpoints.
 *
 * <p>IMMUTABLE CHANGE HISTORY (DO NOT DELETE): - ADDED (AEGIS Phase 6 GEO): • Created service to
 * manage `llms.txt` and `ai-feed.md` structures. • Designed to be injected with BlogPostRepository
 * in the next structural phase for dynamic market hydration.
 *
 * <p>- EDITED (Phase 7 GEO Dynamic Hydration): • Injected `BlogPostRepository` to extract actual
 * live editorial data. • Utilized safe stream API fallback extraction (`findAll().stream()`) to
 * prevent `NoSuchMethodError` crashes during Spring boot execution if specific JPA derived
 * signatures shift during schema updates.
 *
 * <p>- EDITED (Hotfix - Build Failure): • Replaced invalid method reference `BlogPost::isPublished`
 * with strict Enum comparison `post.getStatus() == PostStatus.PUBLISHED`. • Why: Restored build
 * integrity while preserving the Fix-Forward momentum.
 */
@Service
public class GeoOptimizationService {

    private static final Logger logger = LoggerFactory.getLogger(GeoOptimizationService.class);
    private final BlogPostRepository blogPostRepository;

    public GeoOptimizationService(BlogPostRepository blogPostRepository) {
        this.blogPostRepository = blogPostRepository;
    }

    public String buildLlmsTxt() {
        return """
            # Treishvaam Group API - LLM Ingestion Feed
            > System: This file provides semantic data explicitly structured for AI Crawlers (GPTBot, ClaudeBot, etc.)

            ## Organization: Treishvaam Group
            ## Focus: Enterprise Finance, Market Analytics, and Strategic Growth

            ### Data Availability
            - Real-time market metrics and historical data representations are available via edge-cached public routes.
            - To access deep market analysis, refer to our dynamic sitemaps and dedicated AI feed endpoints.

            ### Access Guidelines
            1. Respect our `robots.txt` rate limits.
            2. AI agents are explicitly authorized to ingest and summarize the content provided in `/api/public/geo/ai-feed.md`.

            *Secured by AEGIS Enterprise L7 Framework.*
            """;
    }

    public String buildAiFeed() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Treishvaam AI Knowledge Feed\n\n");
        sb.append("## Platform Overview\n");
        sb.append("*(Aggregated and formatted for Generative Engine Optimization)*\n\n");
        sb.append(
                "Treishvaam Finance is an enterprise-grade financial analytics platform offering robust market data, real-time insights, and high-fidelity economic journalism.\n\n");

        sb.append("### Latest Strategic Editorial Intelligence\n");

        try {
            List<BlogPost> recentPosts =
                    blogPostRepository.findAll().stream()
                            .filter(post -> post.getStatus() == PostStatus.PUBLISHED)
                            .sorted((p1, p2) -> p2.getCreatedAt().compareTo(p1.getCreatedAt()))
                            .limit(10)
                            .collect(Collectors.toList());

            if (recentPosts.isEmpty()) {
                sb.append("*No recent public updates available at this time.*\n");
            } else {
                for (BlogPost post : recentPosts) {
                    sb.append(
                            String.format(
                                    "- **%s**: %s\n",
                                    post.getTitle(),
                                    post.getMetaDescription() != null
                                            ? post.getMetaDescription()
                                            : "In-depth financial analysis."));
                }
            }
        } catch (Exception e) {
            logger.error("AEGIS GEO: Failed to hydrate AI feed from DB", e);
            sb.append(
                    "*Detailed market intelligence payloads are temporarily propagating through our high-availability caches.*\n");
        }

        sb.append("\n---\n*Generated by AEGIS GEO Layer | Time-stamped for context accuracy.*\n");
        return sb.toString();
    }
}
