package com.treishvaam.financeapi.analytics;

import java.util.List;

/**
 * AI-CONTEXT:
 *
 * <p>Purpose: - DTO for aggregating multiple AudienceVisit sessions under a single physical device
 * fingerprint.
 *
 * <p>Scope: - Serves the Audience Dashboard to group incognito and standard sessions seamlessly.
 *
 * <p>Critical Dependencies: - Backend: Generated by AnalyticsService for the Audience Dashboard
 * API.
 *
 * <p>Security Constraints: - deviceFingerprint is a one-way SHA3-256 hash. Raw IPs are never
 * exposed to the frontend.
 *
 * <p>Non-Negotiables: - Must contain the nested List of individual AudienceDataDto sessions.
 *
 * <p>Change Intent: - Facilitate the UI grouping of fragmented browser sessions under a unified
 * hardware profile.
 *
 * <p>Future AI Guidance: - Sort the inner `sessions` list by most recent visit descending before
 * returning this DTO.
 *
 * <p>IMMUTABLE CHANGE HISTORY (DO NOT DELETE): - ADDED: • Created GroupedAudienceDataDto to support
 * Zero-Trust device clustering in the UI. • 2026-08-05 / Incident 41
 *
 * <p>- STRATEGIC PIVOTS & FAILED ATTEMPTS (CRITICAL FOR FUTURE AI): • Strategy Attempted: N/A •
 * Failure Mode: N/A • Date/Phase: 2026-08-05 • Future AI Warning: N/A
 */
public class GroupedAudienceDataDto {
    private String fingerprintId;
    private String deviceBrand;
    private String deviceClass;
    private String deviceModel;
    private String operatingSystem;
    private String osVersion;
    private int totalGroupedSessions;
    private String lastSeen;
    private List<AudienceDataDto> sessions;

    public GroupedAudienceDataDto() {}

    public GroupedAudienceDataDto(
            String fingerprintId,
            String deviceBrand,
            String deviceClass,
            String deviceModel,
            String operatingSystem,
            String osVersion,
            int totalGroupedSessions,
            String lastSeen,
            List<AudienceDataDto> sessions) {
        this.fingerprintId = fingerprintId;
        this.deviceBrand = deviceBrand;
        this.deviceClass = deviceClass;
        this.deviceModel = deviceModel;
        this.operatingSystem = operatingSystem;
        this.osVersion = osVersion;
        this.totalGroupedSessions = totalGroupedSessions;
        this.lastSeen = lastSeen;
        this.sessions = sessions;
    }

    public String getFingerprintId() {
        return fingerprintId;
    }

    public void setFingerprintId(String fingerprintId) {
        this.fingerprintId = fingerprintId;
    }

    public String getDeviceBrand() {
        return deviceBrand;
    }

    public void setDeviceBrand(String deviceBrand) {
        this.deviceBrand = deviceBrand;
    }

    public String getDeviceClass() {
        return deviceClass;
    }

    public void setDeviceClass(String deviceClass) {
        this.deviceClass = deviceClass;
    }

    public String getDeviceModel() {
        return deviceModel;
    }

    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
    }

    public String getOperatingSystem() {
        return operatingSystem;
    }

    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    public String getOsVersion() {
        return osVersion;
    }

    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    public int getTotalGroupedSessions() {
        return totalGroupedSessions;
    }

    public void setTotalGroupedSessions(int totalGroupedSessions) {
        this.totalGroupedSessions = totalGroupedSessions;
    }

    public String getLastSeen() {
        return lastSeen;
    }

    public void setLastSeen(String lastSeen) {
        this.lastSeen = lastSeen;
    }

    public List<AudienceDataDto> getSessions() {
        return sessions;
    }

    public void setSessions(List<AudienceDataDto> sessions) {
        this.sessions = sessions;
    }
}
