/**
 * AI-CONTEXT:
 *
 * <p>Purpose: - AEL Interpreter and Execution Engine. Evaluates generated ANTLR4 Abstract Syntax
 * Trees (AST).
 *
 * <p>Scope: - Consumes parsed AEL rules and executes them against the current Request/Session
 * security context.
 *
 * <p>Critical Dependencies: - Backend: Depends on build-time generated ANTLR classes
 * (`aegisBaseVisitor`, `aegisLexer`, etc).
 *
 * <p>Security Constraints: - Executions must be strictly stateless and side-effect free during the
 * condition evaluation phase.
 *
 * <p>Non-Negotiables: - Must operate in under 5ms to avoid degrading API latency (evaluated within
 * Virtual Threads by L8-BCSM).
 *
 * <p>Change Intent: - Phase 5: Created AEL Interpreter to allow security operators to deploy new
 * rules without code deployments.
 *
 * <p>Future AI Guidance: - Expand the `visitBehavioralExpr` and `visitCryptoExpr` methods to hook
 * into actual Redis datasets and BIE metrics.
 *
 * <p>IMMUTABLE CHANGE HISTORY (DO NOT DELETE): - ADDED: • Implemented `AegisExpressionLanguage` AST
 * Visitor. • Why it was added: Provides the runtime evaluation engine for the formal grammar. •
 * Date: 2026-05-22
 *
 * <p>- DO-NOT-DELETE RULE: This IMMUTABLE CHANGE HISTORY section must never be deleted, truncated,
 * rewritten, or regenerated. Future AI must append only.
 */
package com.treishvaam.financeapi.security.aegis.ael;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * Note: aegisBaseVisitor is automatically generated by the antlr4-maven-plugin during the compile
 * phase. It will not exist in the source directory until a Maven build is executed.
 */
@Component
@Slf4j
public class AegisExpressionLanguage extends aegisBaseVisitor<Boolean> {

  // Context object injected per evaluation containing the current request parameters
  private EvaluationContext currentContext;

  public boolean evaluateCondition(
      aegisParser.ConditionContext ctx, EvaluationContext evaluationContext) {
    this.currentContext = evaluationContext;
    return visit(ctx);
  }

  @Override
  public Boolean visitCondition(aegisParser.ConditionContext ctx) {
    if (ctx.expr() != null) {
      return visit(ctx.expr());
    }

    if (ctx.getChildCount() == 3) {
      if (ctx.getChild(0).getText().equals("(")) {
        return visit(ctx.condition(0));
      }

      String op = ctx.getChild(1).getText();
      boolean left = visit(ctx.condition(0));

      // Short-circuit evaluation
      if (op.equals("AND")) {
        return left && visit(ctx.condition(1));
      } else if (op.equals("OR")) {
        return left || visit(ctx.condition(1));
      }
    } else if (ctx.getChildCount() == 2 && ctx.getChild(0).getText().equals("NOT")) {
      return !visit(ctx.condition(0));
    }

    return false;
  }

  @Override
  public Boolean visitBehavioralExpr(aegisParser.BehavioralExprContext ctx) {
    // Scaffold evaluation - hooks into L5-BIE real-time metrics
    String metric = ctx.getChild(1).getText(); // e.g. BOT_SCORE
    String comparator = ctx.comparator().getText();
    double value = Double.parseDouble(ctx.NUMBER().getText());

    double contextValue = currentContext.getBehavioralMetric(metric);
    return applyComparator(contextValue, comparator, value);
  }

  @Override
  public Boolean visitCryptoExpr(aegisParser.CryptoExprContext ctx) {
    String flag = ctx.getChild(1).getText();
    boolean hasFlag = currentContext.hasCryptoFlag(flag);

    if (ctx.comparator() != null) {
      double value = Double.parseDouble(ctx.NUMBER().getText());
      double contextValue = hasFlag ? 1.0 : 0.0;
      return applyComparator(contextValue, ctx.comparator().getText(), value);
    }
    return hasFlag;
  }

  @Override
  public Boolean visitNetworkExpr(aegisParser.NetworkExprContext ctx) {
    String property = ctx.getChild(1).getText();
    String contextValue = currentContext.getNetworkProperty(property);

    if (ctx.comparator() != null) {
      String comparator = ctx.comparator().getText();
      String targetValue = ctx.getChild(3).getText().replace("\"", ""); // Handle String

      if (comparator.equals("==")) {
        return targetValue.equals(contextValue);
      } else if (comparator.equals("!=")) {
        return !targetValue.equals(contextValue);
      }
    }
    return contextValue != null;
  }

  private boolean applyComparator(double left, String op, double right) {
    switch (op) {
      case ">":
        return left > right;
      case "<":
        return left < right;
      case ">=":
        return left >= right;
      case "<=":
        return left <= right;
      case "==":
        return left == right;
      case "!=":
        return left != right;
      default:
        return false;
    }
  }

  /** Represents the real-time request context loaded with data from Redis/Filters */
  public interface EvaluationContext {
    double getBehavioralMetric(String metric);

    boolean hasCryptoFlag(String flag);

    String getNetworkProperty(String property);
  }
}
