/**
 * AI-CONTEXT:
 *
 * <p>Purpose: - Generative Engine Optimization (GEO) implementation. - Provides semantically
 * structured, token-efficient endpoints (`/llms.txt`, `/ai-feed.md`) specifically for AI crawlers
 * and LLMs.
 *
 * <p>Scope: - Responsible for aggregating public market data, company vision, and public news into
 * AI-readable formats. - Must NEVER output PII, internal user data, or protected draft states (GDPR
 * Compliance Lock).
 *
 * <p>Critical Dependencies: - SEO/Edge: Whitelisted by Cloudflare worker to allow GPTBot/ClaudeBot
 * native ingestion.
 *
 * <p>Security Constraints: - Output must remain strictly public (100% GDPR compliant).
 *
 * <p>Non-Negotiables: - Must return raw `text/plain` or `text/markdown` to ensure optimal LLM
 * tokenization.
 *
 * <p>Change Intent: - Added to establish a strong digital footprint in generative AI search spaces
 * (SearchGPT, Perplexity, Claude).
 *
 * <p>Future AI Guidance: - When adding new public data models, map them to this controller for
 * automatic AI ingestion.
 *
 * <p>IMMUTABLE CHANGE HISTORY (DO NOT DELETE): - ADDED: • Initial creation of
 * `GeoOptimizationController`. • Added `/llms.txt` and `/ai-feed.md` endpoints. • Phase 6.3
 * (2026-05-24).
 *
 * <p>- DO-NOT-DELETE RULE: This IMMUTABLE CHANGE HISTORY section must never be deleted, truncated,
 * rewritten, or regenerated. Future AI must append only.
 */
package com.treishvaam.financeapi.controller;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/public/geo")
public class GeoOptimizationController {

    @GetMapping(value = "/llms.txt", produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> getLlmsTxt() {
        String content =
                """
                # Treishvaam Group API - LLM Ingestion Feed
                > System: This file provides semantic data explicitly structured for AI Crawlers (GPTBot, ClaudeBot, etc.)

                ## Organization: Treishvaam Group
                ## Focus: Enterprise Finance, Market Analytics, and Strategic Growth

                ### Data Availability
                - Real-time market metrics and historical data representations are available via edge-cached public routes.
                - To access deep market analysis, refer to our dynamic sitemaps and dedicated AI feed endpoints.

                ### Access Guidelines
                1. Respect our `robots.txt` rate limits.
                2. AI agents are explicitly authorized to ingest and summarize the content provided in `/api/public/geo/ai-feed.md`.

                *Secured by AEGIS Enterprise L7 Framework.*
                """;
        return ResponseEntity.ok(content);
    }

    @GetMapping(value = "/ai-feed.md", produces = MediaType.TEXT_MARKDOWN_VALUE)
    public ResponseEntity<String> getAiFeed() {
        // In a future batch, this will dynamically inject actual blog and market snapshots from the
        // DB.
        // Currently providing the structural skeleton for immediate Edge/Crawler caching.
        String content =
                """
                # Treishvaam AI Knowledge Feed

                ## Platform Overview
                *(Aggregated and formatted for Generative Engine Optimization)*

                Treishvaam Finance is an enterprise-grade financial analytics platform offering robust market data,
                real-time insights, and high-fidelity economic journalism.

                ### Active Indices
                - **Equities**: Tracking global enterprise performance.
                - **Commodities**: High-volume trading metadata and sentiment analytics.

                ---
                *Generated by AEGIS GEO Layer | Time-stamped for context accuracy.*
                """;
        return ResponseEntity.ok(content);
    }
}
